name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.0-preview.5.20278.1'
      - name: Install dependencies
        working-directory: ./QPM
        run: dotnet restore
      - name: Build ubuntu-x64
        working-directory: ./QPM
        run: dotnet publish -r ubuntu-x64 -c Release /p:PublishSingleFile=true
      - name: Build win-x64
        working-directory: ./QPM
        run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true
      - name: Artifact Upload ubuntu-x64
        uses: actions/upload-artifact@v2
        with:
          name: QPM-ubuntu-x64
          path: QPM/bin/ubuntu-x64/publish/QPM
      - name: Artifact Upload win-x64
        uses: actions/upload-artifact@v2
        with:
          name: QPM-win-x64
          path: QPM/bin/win-x64/publish/QPM.exe
  checks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.0-preview.5.20278.1'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
